services:
  web:
    image: currency-api
    ports:
      - 8080:8080
    depends_on:
      - db
  db:
    container_name: postgres
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432